jobs:
  - name: plv2multiimg-mf1
    type: manifest
    steps:
      - IN: plv2-image1
        pull: false
      - IN: plv2-image2
      - IN: plv2-image3
      - IN: plv2-tpdopts
      - IN: plv2-params1
        applyTo:
          - plv2-image3
      - TASK: managed
      - IN: triggerv2sp1
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
     
  - name: plv2-manifest2
    type: manifest
    steps:
      - IN: plv2-image1
      - TASK: managed
      - IN: triggerv2sp2
      - IN: plv2-params2
      - IN: plv2-dopts1
      - IN: plv2-scale1
      
  - name: plv2-mftomf3
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: plv2-manifest2
      - TASK: managed
      
  - name: plv2-manifest4
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: plv2-tpdopts
      - IN: triggerv2sp4
      - TASK: managed
      
  - name: plv2-manifest5
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: triggerv2sp5
      - IN: plv2ecs-OtherDOpts
      - TASK: managed
      
  - name: plv2upgrade-manifest6
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: triggerv2sp6
      #- IN: plv2ecs-dopts5
      - TASK: managed
      
  - name: plv2gke-manifest7
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: triggerv2sp7
      - IN: plv2gke-dopts4
      - TASK: managed
      
  - name: plv2ecs-manifest8
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: triggerv2sp8
      - IN: plv2ecs-dopts6
      - TASK: managed

  - name: release-version1
    type: release
    steps:
      - IN: plv2-version
      - IN: plv2-manifest1
      - IN: triggerv2sp2
      - TASK: managed
        bump: minor
        
  - name: plv2-ddcdeploy
    type: ddcDeploy
    steps:
      - IN: plv2-manifest2
      - IN: ddc-cluster
      - IN: plv2-opts2
      - TASK: managed

 # - name: b-mon-dcl
  #  type: dclDeploy
   # steps:
    #  - IN: plv2-manifest2
     # - IN: dcl-cluster
      #- TASK: managed

  - name: plv2-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: plv2-manifest2
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: plv2-gkedeploy
    type: gkeDeploy
    steps:
      - IN: plv2gke-manifest7
      - IN: gke-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: plv2-tripubdeploy1
    type: tripubDeploy
    steps:
      - IN: plv2-manifest2
      - IN: tripub-cluster1
      - IN: plv2-tpdopts1
      - TASK: managed
        deployMethod: upgrade
        
  - name: plv2-tripubdeploy8
    type: tripubDeploy
    steps:
      - IN: plv2tp-manifest9
      - IN: tripub-cluster3
      - TASK: managed
        deployMethod: upgrade
       
  #- name: plv2-tripubdeploy9
   # type: tripubDeploy
    #steps:
     # - IN: plv2tp-manifest9
      #- IN: tripub-cluster3
      #- TASK: managed
       # deployMethod: blueGreen

  - name: plv2multimf-tripubdeploy2
    type: tripubDeploy
    steps:
      - IN: plv2-manifest2
      - IN: plv2-manifest4
      - IN: tripub-cluster2
      - IN: plv2-tpdopts
      - TASK: managed
        deployMethod: blueGreen
        
  - name: plv2mftomf-tripubdeploy2
    type: tripubDeploy
    steps:
      - IN: plv2-mftomf3
      - IN: tripub-cluster2
      - IN: plv2-tpdopts1
      - TASK: managed
        deployMethod: blueGreen
        
  - name: plv2-ecsdeploy2
    type: ecsDeploy
    steps:
      - IN: ecs-cluster
      - IN: plv2-manifest5
      - TASK: managed
        deployMethod: upgrade

  - name: plv2upgrade-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: ecs-cluster
      - IN: plv2-invaliddopts3
      - IN: plv2upgrade-manifest6
      - TASK: managed
        deployMethod: upgrade
        
  - name: plv2ecs-ecsdeploy7
    type: ecsDeploy
    steps:
      - IN: ecs-cluster
      - IN: plv2ecs-manifest8
      - TASK: managed
        deployMethod: upgrade

