jobs:
  - name: plv2multiimg-mf1
    type: manifest
    steps:
      - IN: plv2-image1
        pull: false
      - IN: plv2-image2
      - IN: plv2-image3
      - IN: plv2-params1
        applyTo:
          - plv2-image3
      - IN: triggerv2sp1
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
     
  - name: plv2-manifest2
    type: manifest
    steps:
      - IN: plv2-image1
      - TASK: managed
      - IN: triggerv2sp2
      - IN: plv2-params2
      
  - name: plv2-mftomf3
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: plv2-manifest2
      - TASK: managed
      
  - name: plv2-manifest4
    type: manifest
    steps:
      - IN: plv2-image2
      - IN: triggerv2sp4
      
  - name: plv2-manifest5entrypointdopt
    type: manifest
    steps:
      - IN: plv2-image4entrypoint
      - IN: plv2tp-dopts2
      - IN: triggerv2sp4
      
  - name: plv2-manifest6workingdopt
    type: manifest
    steps:
      - IN: plv2-image5workingdir
      - IN: plv2tp-dopts1
      - IN: triggerv2sp4
      
  - name: plv2-manifest7envvar
    type: manifest
    steps:
      - IN: plv2-image3env
      - IN: plv2-params2
      - IN: triggerv2sp4
      
  - name: release-version1
    type: release
    steps:
      - IN: plv2-version
      - IN: plv2-manifest1
      - IN: triggerv2sp2
      - TASK: managed
        bump: alpha
        
  - name: plv2-ddcdeploy
    type: ddcDeploy
    steps:
      - IN: plv2-manifest2
      - IN: ddc-cluster

  - name: plv2-dcldeploy
    type: dclDeploy
    steps:
      - IN: plv2-manifest2
      - IN: dcl-cluster

  - name: plv2-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: plv2-manifest2
      - IN: ecs-cluster

  - name: plv2-gkedeploy
    type: gkeDeploy
    steps:
      - IN: plv2-manifest2
      - IN: gke-cluster

  - name: plv2-tripubdeploy
    type: tripubDeploy
    steps:
      - IN: plv2-manifest2
      - IN: tripub-cluster
      
  - name: plv2multimf-tripubdeploy2
    type: tripubDeploy
    steps:
      - IN: plv2-manifest2
      - IN: plv2-manifest4
      - IN: tripub-cluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: plv2mftomf-tripubdeploy2
    type: tripubDeploy
    steps:
      - IN: plv2-mftomf3
      - IN: tripub-cluster
      - TASK: managed
        deployMethod: blueGreen
