triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 9
       
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 12
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 11
       
   - name: triggerv2sp4
     type: trigger
     version:
       counter: 12
       
   - name: triggerv2sp5
     type: trigger
     version:
       counter: 10
