triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 9
       
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 13
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 11
       
   - name: triggerv2sp4
     type: trigger
     version:
       counter: 13
       
   - name: triggerv2sp5
     type: trigger
     version:
       counter: 18
       
   - name: triggerv2sp6
     type: trigger
     version:
       counter: 6
       
   - name: triggerv2sp7
     type: trigger
     version:
       counter: 9
       
   - name: triggerv2sp8
     type: trigger
     version:
       counter: 1
